/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ContestIdIndexRouteImport } from './routes/contest.$id.index'
import { Route as ContestIdPhotosRouteImport } from './routes/contest.$id.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIdIndexRoute = ContestIdIndexRouteImport.update({
  id: '/contest/$id/',
  path: '/contest/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIdPhotosRoute = ContestIdPhotosRouteImport.update({
  id: '/contest/$id/photos',
  path: '/contest/$id/photos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/photos': typeof PhotosRoute
  '/contest/$id/photos': typeof ContestIdPhotosRoute
  '/contest/$id/': typeof ContestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/photos': typeof PhotosRoute
  '/contest/$id/photos': typeof ContestIdPhotosRoute
  '/contest/$id': typeof ContestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/photos': typeof PhotosRoute
  '/contest/$id/photos': typeof ContestIdPhotosRoute
  '/contest/$id/': typeof ContestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/photos' | '/contest/$id/photos' | '/contest/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/photos' | '/contest/$id/photos' | '/contest/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/photos'
    | '/contest/$id/photos'
    | '/contest/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PhotosRoute: typeof PhotosRoute
  ContestIdPhotosRoute: typeof ContestIdPhotosRoute
  ContestIdIndexRoute: typeof ContestIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$id/': {
      id: '/contest/$id/'
      path: '/contest/$id'
      fullPath: '/contest/$id/'
      preLoaderRoute: typeof ContestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/$id/photos': {
      id: '/contest/$id/photos'
      path: '/contest/$id/photos'
      fullPath: '/contest/$id/photos'
      preLoaderRoute: typeof ContestIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PhotosRoute: PhotosRoute,
  ContestIdPhotosRoute: ContestIdPhotosRoute,
  ContestIdIndexRoute: ContestIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
